### ISSUE TITLE
Docs on how to set up dev environment

### ISSUE THREAD

**Issue by Gaelan** [TPPIDev/TPPI-Tweaks#84]
I'd love to help out (want to add ore generation info as a "recipe" in NEI), but I don't understand how to set up a dev environment for this mod. I git cloned the repo, and ran `./gradlew runClient`. I got a lot of messages about missing mods. I'm unsure as to how to go forward: do I somehow add the mods into the dev environment (I don't see a mods folder), or do something completely different? Docs on this would be great.

**Comment by TehNut** [comment]
The exact same way you setup any other mod.

`gradlew setupDecompWorkspace [eclipse|idea]`

Once that's done, you need to get your hands on a deobfuscated version of each mod we tweak, put them in `/libs/`, and add them to your classpath.
